### ISSUE TITLE
Unable to run the release

### ISSUE THREAD

**Issue by am0d** [Fabien-Chouteau/eagle-lander#1]
The v1.0 release file, which contains the compiled version of eagle lander, doesn't run on my machine because there are a number of dlls missing, specifically:
- libgcc_c_dw2-1.dll
- libcairo-2.dll
- libgdk-3-0.dll
- libgdk_pixbuf-2.0-0.dll

If you could perhaps include them in the release, that would be great!

**Comment by Fabien-Chouteau** [comment]
My bad, you have to install GTKada.
1. Go to this page: http://libre.adacore.com/download/configurations
2. Select the "x86 Windows (32 bits)" platform
3. Download gtkada-gpl-2015-x86-windows-bin.exe under the "GthAda GPL 2015" section
4. Install

Please confirm if this works.

Thanks,

**Comment by am0d** [comment]
I just installed `gtkada-gpl-2015-x86-windows-bin.exe`, but I still get the same errors when trying to run the application.
I ended up copying all the dll files form the gtk-ada installation folder into the location where I unzipped the release folder, and then it ran.  I did try to work out the minimal number of dlls files required, but gave up after I copied 15 of them over.

**Comment by Fabien-Chouteau** [comment]
So my binary release is not useful at all :) Since it's easier to directly compile the code, I should probably remove it...
